const Employee=[
    {
        id:"100",
        uname:"reymond",
        age:"25",
        desg:"developer",
        salary:"22000"
    },
    {
        id:"101",
        uname:"hussain",
        age:"23",
        desg:"developer",
        salary:"18000"
    },
    {
        id:"103",
        uname:"jishna",
        age:"28",
        desg:"developer",
        salary:"29000"
    },
    {
        id:"104",
        uname:"reethu",
        age:"30",
        desg:"developer",
        salary:"36000"
    },
    {
        id:"105",
        uname:"shajmil",
        age:"26",
        desg:"developer",
        salary:"24000"
    },
    
]
export default Employee